version: '3'

services:
  tiler:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GDAL_CACHEMAX=512
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      - CPL_TMPDIR=/tmp
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - PYTHONWARNINGS=ignore
      - GDAL_DISABLE_READDIR_ON_OPEN=empty_dir
      - MEMCACHED_HOST=0.0.0.0

  memcached:
    image: memcached
    ports:
      - "11211:11211"